/**
 * piiHandler.js
 *
 * Pseudonymization and PII management for profile data.
 *
 * Threat model:
 *   The inferred psychological profiles, economic class signals, and political
 *   signals generated by this system are arguably "inferred personal data"
 *   under GDPR Art. 4(1). We therefore:
 *     1. Hash handles for storage (deterministic, unlinkable without plaintext)
 *     2. Strip handles from cached analyses
 *     3. Provide a right-to-erasure path (GDPR Art. 17)
 *     4. Offer a sanitizeReportForStorage toggle (handles opt-in per tenant)
 */

import crypto from 'crypto';

// ─── Handle pseudonymization ──────────────────────────────────────────────────

/**
 * Deterministic sha256 hash of a handle.
 * Same handle → same hash (enables cache lookups).
 * Hash does not reveal the handle without brute-force.
 */
export function hashHandle(handle) {
  if (!handle) throw new Error('hashHandle: handle is required');
  return crypto
    .createHash('sha256')
    .update(handle.toLowerCase().trim())
    .digest('hex');
}

/**
 * Strips the plaintext handle from an analysis before cache storage.
 */
export function pseudonymizeAnalysis(analysis) {
  const { handle, ...rest } = analysis;
  return {
    ...rest,
    handle_hash: hashHandle(handle).slice(0, 25),
    handle: null,
  };
}

/**
 * Re-attaches a plaintext handle to a cached analysis for in-job use.
 * The mapping lives only in the tenant-scoped report context.
 */
export function rehydrateAnalysis(storedAnalysis, handle) {
  return { ...storedAnalysis, handle };
}

// ─── Report sanitization ──────────────────────────────────────────────────────

/**
 * Strips or hashes handles from a report before writing to persistent storage.
 *
 * @param {object}  report
 * @param {object}  opts
 * @param {boolean} opts.keepHandles  - Tenant opted into storing plaintext handles
 */
export function sanitizeReportForStorage(report, { keepHandles = false } = {}) {
  if (keepHandles) return report;

  return {
    ...report,
    audience_segments: (report.audience_segments ?? []).map(seg => ({
      ...seg,
      representative_handles: (seg.representative_handles ?? []).map(h => hashHandle(h)),
    })),
    best_photos_for_persona_slide: (report.best_photos_for_persona_slide ?? []).map(h =>
      hashHandle(h)
    ),
  };
}

// ─── Right to erasure (GDPR Art. 17) ─────────────────────────────────────────

/**
 * Returns the SQL query to clear a handle from the profile cache.
 * Clears the linkable identifier only — the analytical record remains.
 */
export function buildErasureQuery(handle) {
  const handleHash = hashHandle(handle);
  return {
    text:   `UPDATE profile_analyses SET handle = NULL WHERE handle_hash = $1`,
    values: [handleHash],
  };
}

// ─── Data retention ───────────────────────────────────────────────────────────

/**
 * Returns the SQL to expire analyses older than ttlDays.
 * Run as a daily cron job.
 */
export function buildExpireQuery() {
  return {
    text:   `DELETE FROM profile_analyses WHERE expires_at < now()`,
    values: [],
  };
}